services:
  - type: web
    name: smishguard
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --workers 1 --timeout 180 --preload app:app  # ‚Üê CHANGE THIS LINE